version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fuels_logistics_db
    environment:
      POSTGRES_USER: fuels_user
      POSTGRES_PASSWORD: fuels_password
      POSTGRES_DB: fuels_logistics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fuels_user -d fuels_logistics_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
